[gcloud]
disabled = true
[aws]
disabled = true
[kubernetes]
format = '[⛵ ($context)](dimmed red) '
disabled = true
[kubernetes.context_aliases]
"gke_(?P<var_project>[\\w-]+)_.*_(?P<var_cluster>[\\w-]+)" = "$var_cluster@$var_project"
