[".local/share/fonts/AppleColorEmoji.ttf"]
    type = "file"
    url = "https://github.com/samuelngs/apple-emoji-linux/releases/download/latest/AppleColorEmoji.ttf"
[".local/share/fonts/Meslo"]
    type = "archive"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Meslo.zip"
