## Fonts
[".local/share/fonts/AppleColorEmoji.ttf"]
	type = "file"
	url = "https://github.com/samuelngs/apple-emoji-linux/releases/download/ios-15.4/AppleColorEmoji.ttf"
[".local/share/fonts/Meslo LG S DZ Bold Italic Nerd Font Complete.ttf"]
	type = "file"
	url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Meslo/S-DZ/Bold-Italic/complete/Meslo%20LG%20S%20DZ%20Bold%20Italic%20Nerd%20Font%20Complete.ttf"
[".local/share/fonts/Meslo LG S DZ Bold Italic Nerd Font Complete Mono.ttf"]
	type = "file"
	url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Meslo/S-DZ/Bold-Italic/complete/Meslo%20LG%20S%20DZ%20Bold%20Italic%20Nerd%20Font%20Complete%20Mono.ttf"
[".local/share/fonts/Meslo LG S DZ Bold Nerd Font Complete.ttf"]
	type = "file"
	url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Meslo/S-DZ/Bold/complete/Meslo%20LG%20S%20DZ%20Bold%20Nerd%20Font%20Complete.ttf"
[".local/share/fonts/Meslo LG S DZ Bold Nerd Font Complete Mono.ttf"]
	type = "file"
	url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Meslo/S-DZ/Bold/complete/Meslo%20LG%20S%20DZ%20Bold%20Nerd%20Font%20Complete%20Mono.ttf"
[".local/share/fonts/Meslo LG S DZ Italic Nerd Font Complete.ttf"]
	type = "file"
	url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Meslo/S-DZ/Italic/complete/Meslo%20LG%20S%20DZ%20Italic%20Nerd%20Font%20Complete.ttf"
[".local/share/fonts/Meslo LG S DZ Italic Nerd Font Complete Mono.ttf"]
	type = "file"
	url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Meslo/S-DZ/Italic/complete/Meslo%20LG%20S%20DZ%20Italic%20Nerd%20Font%20Complete%20Mono.ttf"
[".local/share/fonts/Meslo LG S DZ Regular Nerd Font Complete.ttf"]
	type = "file"
	url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Meslo/S-DZ/Regular/complete/Meslo%20LG%20S%20DZ%20Regular%20Nerd%20Font%20Complete.ttf"
[".local/share/fonts/Meslo LG S DZ Regular Nerd Font Complete Mono.ttf"]
	type = "file"
	url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Meslo/S-DZ/Regular/complete/Meslo%20LG%20S%20DZ%20Regular%20Nerd%20Font%20Complete%20Mono.ttf"

## ZSH plugins
#[".config/zsh/plugins/zsh-vi-mode.zsh"]
#	type = "file"
#	url = "https://raw.githubusercontent.com/jeffreytse/zsh-vi-mode/master/zsh-vi-mode.zsh"
#	refreshPeriod = "672h"

## https://github.com/terraform-linters/tflint
[".local/bin"]
	type = "archive"
	url = "https://github.com/terraform-linters/tflint/releases/download/v0.36.2/tflint_linux_amd64.zip"

## https://github.com/terraform-linters/tflint
[".local/bin/swayshot"]
	type = "file"
	url = "https://gitlab.com/radio_rogal/swayshot/-/raw/master/swayshot.sh"
	executable = true

## https://github.com/hidetatz/kubecolor
[".local/bin/kubecolor"]
	type = "file"
	url = "https://github.com/hidetatz/kubecolor/releases/download/v0.0.20/kubecolor_0.0.20_Linux_x86_64.tar.gz"
	#exact = true
	executable = true
	refreshPeriod = "168h"
	filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "kubecolor"]


## Nyoom
#[".config/nvim"]
#	type = "git-repo"
#	url = "git@github.com:AlexLov/nyoom.nvim.git"

## Tmux Plugin manager
[".config/tmux/plugins/tpm"]
	type = "git-repo"
	url = "https://github.com/tmux-plugins/tpm"

## Neovim impatient plugin
[".local/share/nvim/site/pack/packer/start/impatient.nvim"]
	type = "git-repo"
	url = "https://github.com/lewis6991/impatient.nvim"

## Neovim tangerin plugin
[".local/share/nvim/site/pack/packer/start/tangerin.nvim"]
	type = "git-repo"
	url = "https://github.com/udayvir-singh/tangerine.nvim"

## Neovim hibiscus plugin (accompany tangerine with useful macroses)
[".local/share/nvim/site/pack/packer/start/hibiscus.nvim"]
	type = "git-repo"
	url = "https://github.com/udayvir-singh/hibiscus.nvim"

## Neovim Packer plugin
[".local/share/nvim/site/pack/packer/start/packed.nvim"]
	type = "git-repo"
	url = "https://github.com/wbthomason/packer.nvim"

## Catppuccin colorsheme for bat
[".config/bat/themes/Catppuccin-mocha.tmTheme"]
	type = "file"
	url = "https://raw.githubusercontent.com/catppuccin/bat/main/Catppuccin-mocha.tmTheme"
  refreshPeriod = "168h"

## Catppuccin colorsheme for foot
[".config/foot/catppuccin-mocha.color.ini"]
	type = "file"
	url = "https://raw.githubusercontent.com/catppuccin/foot/main/catppuccin-mocha.conf"
  refreshPeriod = "168h"

# vim: ts=2 noet
