if [[ -n $ZDOTDIR ]]; then
	ZSH_CONFIGS_DIR="${ZDOTDIR}/conf.d"
	ZSH_PLUGINS_DIR="${ZDOTDIR}/plugins"
fi

if [[ -d "$ZSH_CONFIGS_DIR" ]]; then
  for config_file in $(ls -1 ${ZSH_CONFIGS_DIR}/*.zsh); do
    . "${config_file}"
  done
fi

if [[ -d "$ZSH_PLUGINS_DIR" ]]; then
  for plugin_file in $(ls -1 ${ZSH_PLUGINS_DIR}/*.zsh); do
    . "${plugin_file}"
  done
fi

## TODO
zle_highlight=('paste:none')
