if [[ -n $ZDOTDIR ]]; then
	ZSH_CONFIGS_DIR="${ZDOTDIR}/conf.d"
	ZSH_PLUGINS_DIR="${ZDOTDIR}/plugins"
fi

if [[ -d "$ZSH_CONFIGS_DIR" ]]; then
  for config_file in $(find ${ZSH_CONFIGS_DIR} -type f -iname '*.zsh'); do
    . "${config_file}"
  done
fi

if [[ -d "$ZSH_PLUGINS_DIR" ]]; then
  for plugin_file in $(find ${ZSH_PLUGINS_DIR} -type f -iname '*.zsh'); do
    . "${plugin_file}"
  done
fi

## TODO
zle_highlight=('paste:none')

# make completion work with kubecolor like it is kubectl
compdef kubecolor=kubectl
